//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idopont
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Idopont()
        {
            this.Szindarab = new HashSet<Szindarab>();
        }
    
        public int IdopontSK { get; set; }
        public System.DateTime EloadasNap { get; set; }
        public Nullable<System.DateTime> Kezdes { get; set; }
        public Nullable<System.DateTime> Befejezes { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szindarab> Szindarab { get; set; }
    }
}
