//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jegytipus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Jegytipus()
        {
            this.Rendelesi_tetel = new HashSet<Rendelesi_tetel>();
        }
    
        public int JegytipusSK { get; set; }
        public string Megnevezes { get; set; }
        public double Egysegar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelesi_tetel> Rendelesi_tetel { get; set; }
    }
}
