//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TicketEntities : DbContext
    {
        public TicketEntities()
            : base("name=TicketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Idopont> Idopont { get; set; }
        public virtual DbSet<Jegytipus> Jegytipus { get; set; }
        public virtual DbSet<Rendeles> Rendeles { get; set; }
        public virtual DbSet<Rendelesi_tetel> Rendelesi_tetel { get; set; }
        public virtual DbSet<Szindarab> Szindarab { get; set; }
        public virtual DbSet<Szinhaz> Szinhaz { get; set; }
        public virtual DbSet<Vevo> Vevo { get; set; }
    }
}
