//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rendelesi_tetel
    {
        public int TetelekSK { get; set; }
        public int RendelesFK { get; set; }
        public int SzindarabFK { get; set; }
        public int JegytipusFK { get; set; }
        public int Mennyiség { get; set; }
    
        public virtual Jegytipus Jegytipus { get; set; }
        public virtual Rendeles Rendeles { get; set; }
        public virtual Szindarab Szindarab { get; set; }
    }
}
