//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szinhaz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szinhaz()
        {
            this.Szindarab = new HashSet<Szindarab>();
        }
    
        public int SzinhazSK { get; set; }
        public string Nev { get; set; }
        public string Helyszin { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Szindarab> Szindarab { get; set; }
    }
}
