//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace khtnnc_projekt
{
    using System;
    using System.Collections.Generic;
    
    public partial class Szindarab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Szindarab()
        {
            this.Rendelesi_tetel = new HashSet<Rendelesi_tetel>();
        }
    
        public int SzindarabSK { get; set; }
        public int SzinhazFK { get; set; }
        public string Cim { get; set; }
        public string Rendezo { get; set; }
        public int IdopontFK { get; set; }
        public int Musorido { get; set; }
        public Nullable<bool> UjDarabE { get; set; }
    
        public virtual Idopont Idopont { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rendelesi_tetel> Rendelesi_tetel { get; set; }
        public virtual Szinhaz Szinhaz { get; set; }
    }
}
